edition = "2024"

imports_granularity = "Module"
group_imports = "StdExternalCrate"
merge_derives = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 20
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true


